version: 2.1

filter_ignore_main_branches: &filter_ignore_main_branches
  filters:
    branches:
      ignore:
#        - master added before for testing ignore branches template features
        - prod

executors:
  machine-executors:
    working_directory: ~/project
    machine:
      image: ubuntu-2004:202008-01

steps:
  - &checkout_code
    checkout:
      path: $CIRCLE_PROJECT_REPONAME

commands:
  checkstyle:
    description: "Code style checking"
    steps:
      - run:
          name: "Running checkstyle"
          command: |
            cd ./$CIRCLE_PROJECT_REPONAME
            chmod +x mvnw
            ./mvnw validate
  build-and-run-test:
    description: "Running test"
    steps:
      - run:
          name: "Running application test"
          environment:
            TERM: dumb
          command: |
            cd ./$CIRCLE_PROJECT_REPONAME
            chmod +x mvnw
            ./mvnw package
  verify-test-coverage:
    description: "Running verify (test coverage)"
    steps:
      - run:
          name: "Running application verify"
          environment:
            TERM: dumb
          command: |
            cd ./$CIRCLE_PROJECT_REPONAME
            chmod +x mvnw
            ./mvnw verify
jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - *checkout_code
      - checkstyle
      - build-and-run-test
      - verify-test-coverage
      - persist_to_workspace:
          root: .
          paths:
            - .
      - store_artifacts:
          path: tutorial/solid/target/solid-1.0.jar
#      - store_artifacts:
#          path: tutorial/algorithm/target/site/cobertura/
      - store_test_results:
          path: tutorial/solid/target/surefire-reports/

workflows:
  version: 2
  build:
    jobs:
      - build:
          <<: *filter_ignore_main_branches


